# Generated by Django 5.1.6 on 2025-03-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='plantao',
            field=models.CharField(blank=True, choices=[('ALFA', 'ALFA - 07:30 às 07:30'), ('BRAVO', 'BRAVO - 07:30 às 07:30'), ('CHARLIE', 'CHARLIE - 07:30 às 07:30'), ('DELTA', 'DELTA - 07:30 às 07:30')], max_length=10, null=True),
        ),
    ]
