# Generated by Django 5.1.6 on 2025-03-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_servidor_plantao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='plantao',
            field=models.CharField(blank=True, choices=[('ALFA', 'ALFA'), ('BRAVO', 'BRAVO'), ('CHARLIE', 'CHARLIE'), ('DELTA', 'DELTA')], max_length=10, null=True),
        ),
    ]
