# Generated by Django 5.1.6 on 2025-03-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_servidor_plantao'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroacesso',
            name='setor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registroacesso',
            name='veiculo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
