# Generated by Django 5.1.6 on 2025-03-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_registroacesso_setor_registroacesso_veiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servidor',
            name='placa_veiculo',
        ),
        migrations.RemoveField(
            model_name='servidor',
            name='plantao',
        ),
        migrations.RemoveField(
            model_name='servidor',
            name='tipo_funcionario',
        ),
        migrations.AddField(
            model_name='servidor',
            name='setor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servidor',
            name='veiculo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
