# Generated by Django 5.1.6 on 2025-03-31 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_tipo_documento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registroacesso',
            name='data_hora_saida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroacesso',
            name='observacao_saida',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='registroacesso',
            name='operador_saida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saidas_registradas', to=settings.AUTH_USER_MODEL),
        ),
    ]
