# Generated by Django 5.1.6 on 2025-03-31 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_registroacesso_data_hora_saida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroacesso',
            name='data_hora_alteracao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroacesso',
            name='registro_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_alterados', to='core.registroacesso'),
        ),
        migrations.AddField(
            model_name='registroacesso',
            name='status_alteracao',
            field=models.CharField(choices=[('ORIGINAL', 'Original'), ('EDITADO', 'Editado'), ('EXCLUIDO', 'Excluído')], default='ORIGINAL', max_length=10),
        ),
    ]
