# Generated by Django 5.1.6 on 2025-04-01 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_registroacesso_data_hora_alteracao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logauditoria',
            options={'ordering': ['-data_hora'], 'verbose_name': 'Log de Auditoria', 'verbose_name_plural': 'Logs de Auditoria'},
        ),
        migrations.AlterModelOptions(
            name='registroacesso',
            options={'ordering': ['-data_hora'], 'verbose_name': 'Registro de Acesso', 'verbose_name_plural': 'Registros de Acesso'},
        ),
        migrations.AlterModelOptions(
            name='servidor',
            options={'ordering': ['nome'], 'verbose_name': 'Servidor', 'verbose_name_plural': 'Servidores'},
        ),
        migrations.RemoveField(
            model_name='registroacesso',
            name='data_hora_manual',
        ),
        migrations.RemoveField(
            model_name='servidor',
            name='data_cadastro',
        ),
        migrations.AddField(
            model_name='servidor',
            name='plantao',
            field=models.CharField(blank=True, choices=[('ALFA', 'ALFA'), ('BRAVO', 'BRAVO'), ('CHARLIE', 'CHARLIE'), ('DELTA', 'DELTA')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='servidor',
            name='tipo_funcionario',
            field=models.CharField(choices=[('PLANTONISTA', 'Plantonista'), ('EXPEDIENTE', 'Expediente'), ('VISITANTE', 'Visitante'), ('TERCEIRIZADO', 'Terceirizado')], default='VISITANTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='objeto_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='tipo_acao',
            field=models.CharField(choices=[('CRIACAO', 'Criação'), ('EDICAO', 'Edição'), ('EXCLUSAO', 'Exclusão')], max_length=10),
        ),
        migrations.AlterField(
            model_name='registroacesso',
            name='data_hora',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='registroacesso',
            name='justificativa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroacesso',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroacesso',
            name='observacao_saida',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroacesso',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registroacesso',
            name='operador_saida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_saida', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registroacesso',
            name='registro_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.registroacesso'),
        ),
        migrations.AlterField(
            model_name='registroacesso',
            name='saida_pendente',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='registroacesso',
            name='status_alteracao',
            field=models.CharField(blank=True, choices=[('ORIGINAL', 'Original'), ('EDITADO', 'Editado'), ('EXCLUIDO', 'Excluído')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='registroacesso',
            name='tipo_acesso',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10),
        ),
        migrations.CreateModel(
            name='RegistroDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acesso', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10)),
                ('data_hora', models.DateTimeField()),
                ('isv', models.BooleanField(default=False)),
                ('veiculo', models.CharField(blank=True, max_length=50, null=True)),
                ('setor', models.CharField(blank=True, max_length=100, null=True)),
                ('data_hora_saida', models.DateTimeField(blank=True, null=True)),
                ('saida_pendente', models.BooleanField(default=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dashboard_registros_criados', to=settings.AUTH_USER_MODEL)),
                ('operador_saida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dashboard_registros_saida', to=settings.AUTH_USER_MODEL)),
                ('registro_historico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.registroacesso')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.servidor')),
            ],
            options={
                'verbose_name': 'Registro do Dashboard',
                'verbose_name_plural': 'Registros do Dashboard',
                'ordering': ['-data_hora'],
            },
        ),
    ]
