# Generated by Django 5.1.6 on 2025-04-01 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_logauditoria_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroacesso',
            options={'ordering': ['-data_hora'], 'verbose_name': 'Histórico', 'verbose_name_plural': 'Histórico'},
        ),
        migrations.AlterModelOptions(
            name='registrodashboard',
            options={'ordering': ['-data_hora'], 'verbose_name': 'Dashboard', 'verbose_name_plural': 'Dashboard'},
        ),
        migrations.AlterField(
            model_name='servidor',
            name='setor',
            field=models.CharField(default='Não Informado', max_length=100),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='veiculo',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(code='placa_invalida', message='Placa inválida. Use o formato AAA0A00 ou AAA0000.', regex='^[A-Z]{3}[0-9][0-9A-Z][0-9]{2}$')]),
        ),
    ]
