# Generated by Django 5.1.6 on 2025-04-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_registroacesso_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título do tutorial', max_length=200)),
                ('descricao', models.TextField(help_text='Descrição detalhada do conteúdo')),
                ('url_video', models.URLField(help_text='URL do vídeo (YouTube, Vimeo, etc.)')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição do tutorial')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o tutorial está visível')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tutorial em Vídeo',
                'verbose_name_plural': 'Tutoriais em Vídeo',
                'ordering': ['ordem', 'titulo'],
            },
        ),
        migrations.AlterField(
            model_name='servidor',
            name='setor',
            field=models.CharField(max_length=100),
        ),
    ]
