# Generated by Django 5.1.6 on 2025-04-06 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_videotutorial_alter_servidor_setor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroTeste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acesso', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('data_hora_saida', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('isv', models.BooleanField(default=False)),
                ('veiculo', models.CharField(blank=True, max_length=10)),
                ('setor', models.CharField(blank=True, max_length=100)),
                ('saida_pendente', models.BooleanField(default=False)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servidor')),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
        migrations.DeleteModel(
            name='VideoTutorial',
        ),
    ]
