# Generated by Django 5.1.6 on 2025-04-06 22:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_registroteste_delete_videotutorial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServidorTreinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero_documento', models.CharField(max_length=20)),
                ('tipo_funcionario', models.CharField(choices=[('PLANTONISTA', 'Plantonista'), ('EXPEDIENTE', 'Expediente'), ('VISITANTE', 'Visitante'), ('TERCEIRIZADO', 'Terceirizado')], default='VISITANTE', max_length=20)),
                ('plantao', models.CharField(blank=True, choices=[('ALFA', 'ALFA'), ('BRAVO', 'BRAVO'), ('CHARLIE', 'CHARLIE'), ('DELTA', 'DELTA')], max_length=10, null=True)),
                ('setor', models.CharField(max_length=100)),
                ('veiculo', models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(code='placa_invalida', message='Placa inválida. Use o formato AAA0A00 ou AAA0000.', regex='^[A-Z]{3}[0-9][0-9A-Z][0-9]{2}$')])),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Servidor (Treinamento)',
                'verbose_name_plural': 'Servidores (Treinamento)',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='VideoTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(choices=[('BASICO', 'Funcionalidades Básicas'), ('AVANCADO', 'Funcionalidades Avançadas'), ('NOVIDADES', 'Novas Funcionalidades'), ('ERROS', 'Correção de Erros Comuns')], max_length=20)),
                ('url_video', models.URLField()),
                ('ordem_exibicao', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vídeo Tutorial',
                'verbose_name_plural': 'Vídeos Tutoriais',
                'ordering': ['categoria', 'ordem_exibicao'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAcessoTreinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acesso', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10)),
                ('data_hora', models.DateTimeField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('isv', models.BooleanField(default=False)),
                ('veiculo', models.CharField(blank=True, max_length=50, null=True)),
                ('setor', models.CharField(blank=True, max_length=100, null=True)),
                ('data_hora_saida', models.DateTimeField(blank=True, null=True)),
                ('observacao_saida', models.TextField(blank=True, null=True)),
                ('saida_pendente', models.BooleanField(default=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_treinamento', to=settings.AUTH_USER_MODEL)),
                ('operador_saida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_saida_treinamento', to=settings.AUTH_USER_MODEL)),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.servidortreinamento')),
            ],
            options={
                'verbose_name': 'Registro (Treinamento)',
                'verbose_name_plural': 'Registros (Treinamento)',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.DeleteModel(
            name='RegistroTeste',
        ),
    ]
