# Generated by Django 5.1.6 on 2025-04-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_servidortreinamento_videotutorial_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videotutorial',
            options={'ordering': ['ordem', 'titulo'], 'verbose_name': 'Vídeo Tutorial', 'verbose_name_plural': 'Vídeos Tutoriais'},
        ),
        migrations.RemoveField(
            model_name='videotutorial',
            name='ordem_exibicao',
        ),
        migrations.RemoveField(
            model_name='videotutorial',
            name='url_video',
        ),
        migrations.AddField(
            model_name='videotutorial',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='videotutorial',
            name='ordem',
            field=models.IntegerField(default=0, help_text='Ordem de exibição do vídeo'),
        ),
        migrations.AddField(
            model_name='videotutorial',
            name='url_youtube',
            field=models.URLField(default='https://www.youtube.com/watch?v=placeholder', help_text='URL do vídeo no YouTube'),
        ),
        migrations.AlterField(
            model_name='videotutorial',
            name='categoria',
            field=models.CharField(choices=[('ENTRADA', 'Registro de Entrada'), ('SAIDA', 'Registro de Saída'), ('EDICAO', 'Edição de Registros'), ('EXCLUSAO', 'Exclusão de Registros'), ('PLANILHA', 'Gerenciamento da Planilha'), ('GERAL', 'Funcionalidades Gerais')], max_length=50),
        ),
    ]
