# Generated by Django 5.1.6 on 2025-04-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='senha_temporaria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='precisa_trocar_senha',
            field=models.BooleanField(default=False),
        ),
    ]
