# Generated by Django 5.2.1 on 2025-06-25 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_perfilusuario_senha_temporaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('OPERADOR', 'Operador'), ('VISUALIZACAO', 'Visualização'), ('STAFF', 'Staff'), ('ADMIN', 'Administrador')], default='OPERADOR', max_length=15),
        ),
    ]
