# Generated by Django 5.2.1 on 2025-06-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_perfilusuario_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='foto_sgp2rr',
            field=models.URLField(blank=True, help_text='URL da foto obtida do SGP2RR', null=True),
        ),
    ]
