# Generated by Django 6.0.6 on 2026-06-17 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_corrigir_prefixo_egresso_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='senha_temporaria',
        ),
    ]
